name: Build C/C++ sources with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select CMake build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - MinSizeRel

env:
  build_type: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download MAVSDK
      run: |
        Invoke-WebRequest -Uri "https://github.com/mavlink/MAVSDK/releases/download/v3.17.0/mavsdk-windows-x64.zip" -OutFile "$env:TEMP\mavsdk.zip"
        Expand-Archive -Path "$env:TEMP\mavsdk.zip" -DestinationPath "C:\mavsdk"

    - name: Configure CMake
      run: |
        cmake -S . -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type || env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ github.event.inputs.build_type || env.BUILD_TYPE }}
